### ISSUE TITLE
Outstanding

### ISSUE THREAD

**Issue by kee007ney** [btroia/basis-data-export#16]
This is fantastic. Since the raw data is pretty much the main thing I'm looking for in a wearable, I might buy the Basis B1 because of this script. My only question is whether you think it will be reasonable for someone like me (who knows very little about programming) to execute it. It looks like I can either copy/paste your code into a Linux client on a virtual machine or put it somewhere my browser can access (which I assume includes somewhere locally) and do it through that route. Does that sound right? If so, I think I can handle that. Is there anything else I should know?
Thanks!!

**Comment by btroia** [comment]
Hi! Unfortunately, you'll need to do a bit more than just copy/paste the code. I've only tested the script on a Mac environment, so you may need to change some of the paths and make sure you have PHP configured properly on your system. Good luck!
