### ISSUE TITLE
Unable to use Method 2 - Via command-line arguments

### ISSUE THREAD

**Issue by akrueger** [btroia/basis-data-export#17]
Interactive mode works fine, but when I use method 2 with the same credentials and date, I receive the following error:

```
Caught exception: ERROR: Unable to login! Check your username and password.
Caught exception: ERROR: Unable to login! Check your username and password.
Caught exception: ERROR: Unable to login! Check your username and password.
```

I'm using the following command:

`php basisdataexport.php -uMyEmail@gmail.com -p*********** -d2015-03-01 -fjson`

**Comment by btroia** [comment]
Are you still having this issue? If so, can you try adding your username and password to [basisdataexport.php](https://github.com/btroia/basis-data-export/blob/master/basisdataexport.php) lines 47 and 48 and running again? You might also want to add some debugging output to ensure the username and password parameters are being set.
